# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       sailfishos-eventsview-controls-attached

# >> macros
BuildArch: armv7hl
# << macros

Summary:    Eventsview controls attached page
Version:    0.0.1
Release:    1
Group:      Qt/Qt
License:    TODO
Source0:    %{name}-%{version}.tar.bz2
Requires:   patchmanager
Requires:   lipstick-jolla-home-qt5 >= 0.24.23.1

%description
Eventsview controls attached page activated by left swipe.


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre



# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
mkdir -p %{buildroot}/usr/share/patchmanager/patches/sailfishos-eventsview-controls-attached
cp -r patch/* %{buildroot}/usr/share/patchmanager/patches/sailfishos-eventsview-controls-attached
mkdir -p %{buildroot}/usr/share/jolla-settings/pages/sailfishos-eventsview-controls-attached
cp -r settings/*.qml %{buildroot}/usr/share/jolla-settings/pages/sailfishos-eventsview-controls-attached
mkdir -p %{buildroot}/usr/share/jolla-settings/entries
cp -r settings/*.json %{buildroot}/usr/share/jolla-settings/entries/
mkdir -p %{buildroot}/usr/share/lipstick-jolla-home-qt5/eventsview
cp -r patch/*.qml %{buildroot}/usr/share/lipstick-jolla-home-qt5/eventsview
# << install pre

# >> install post
# << install post

%pre
# >> pre
if [ -f /usr/sbin/patchmanager ]; then
/usr/sbin/patchmanager -u sailfishos-eventsview-controls-attached || true
fi
# << pre

%preun
# >> preun
if [ -f /usr/sbin/patchmanager ]; then
/usr/sbin/patchmanager -u sailfishos-eventsview-controls-attached || true
fi
# << preun

%files
%defattr(-,root,root,-)
%{_datadir}/patchmanager/patches/sailfishos-eventsview-controls-attached
%{_datadir}/jolla-settings/entries
%{_datadir}/jolla-settings/pages
%{_datadir}/lipstick-jolla-home-qt5/eventsview
# >> files
# << files
